using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolKeeper.Abstractions.Interfaces.Repository;
using SchoolKeeper.Authorization;
using SchoolKeeper.DTO;
using SchoolKeeper.Models.Enums;
using SchoolKeeper.Response;
using SchoolKeeper.Services;

namespace SchoolKeeper.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class ReptController : BaseController<Rept, ReptDto>
    {
        private readonly IUserService _userService;
        private readonly IDataFilterService _dataFilterService;
        private readonly SchoolKeeperDbContext _context;

        public ReptController(
            IGenericRepository<Rept> repo,
            IUserService userService,
            IDataFilterService dataFilterService,
            SchoolKeeperDbContext context) 
            : base(repo)
        {
            _userService = userService;
            _dataFilterService = dataFilterService;
            _context = context;
        }

        public override async Task<ActionResult<ResponseWrapper<IEnumerable<ReptDto>>>> GetAll([FromQuery] int page = 1, [FromQuery] int pageSize = 50)
        {
            var user = await _userService.GetCurrentUserAsync(HttpContext);
            if (user == null) throw new UnauthorizedException();

            // Согласно матрице: Admin, Security, Teacher
            if (user.Role != UserRole.Admin && user.Role != UserRole.Security && user.Role != UserRole.Teacher)
            {
                throw new UnauthorizedException("You don't have access to reports.");
            }

            var query = _context.Reports
                .Include(r => r.School)
                .Include(r => r.Generator)
                .AsQueryable();

            // Filter by school (except Admin)
            if (user.Role != UserRole.Admin)
            {
                query = _dataFilterService.FilterBySchool(query, user.SchoolId);
            }

            if (page <= 0) page = 1;
            if (pageSize <= 0 || pageSize > 500) pageSize = 50;

            var items = await query
                .OrderByDescending(r => r.GeneratedOn)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            var dtos = items.Select(MapToDto).ToList();
            var response = new ResponseWrapper<IEnumerable<ReptDto>>(200, dtos);
            return Ok(response);
        }

        [HttpPost]
        public override async Task<ActionResult<ResponseWrapper<ReptDto>>> Create([FromBody] ReptDto dto)
        {
            var user = await _userService.GetCurrentUserAsync(HttpContext);
            if (user == null) throw new UnauthorizedException();

            // Согласно матрице: Admin, Security, Teacher
            if (user.Role != UserRole.Admin && user.Role != UserRole.Security && user.Role != UserRole.Teacher)
            {
                throw new UnauthorizedException("You don't have permission to create reports.");
            }

            // Set generated by to current user
            dto.GeneratedBy = user.Id;

            // Non-admin users can only create reports for their school
            if (user.Role != UserRole.Admin && dto.SchoolId != user.SchoolId)
            {
                throw new BadRequestException("You can only create reports for your school.");
            }

            // Set generated on to current time if not provided
            if (dto.GeneratedOn == default)
            {
                dto.GeneratedOn = DateTime.UtcNow;
            }

            return await base.Create(dto);
        }

        [HttpPut("{id:int}")]
        public override async Task<ActionResult<ResponseWrapper<ReptDto>>> Update(int id, [FromBody] ReptDto dto)
        {
            var user = await _userService.GetCurrentUserAsync(HttpContext);
            if (user == null) throw new UnauthorizedException();

            // Согласно матрице: Admin, Security, Teacher
            if (user.Role != UserRole.Admin && user.Role != UserRole.Security && user.Role != UserRole.Teacher)
            {
                throw new UnauthorizedException("You don't have permission to update reports.");
            }

            var report = await Repo.GetByIdAsync(id);
            if (report == null) throw new NotFoundException();

            // Check school access
            if (user.Role != UserRole.Admin && report.SchoolId != user.SchoolId)
            {
                throw new UnauthorizedException("You don't have access to this report.");
            }

            return await base.Update(id, dto);
        }

        [HttpGet("{id:int}")]
        public override async Task<ActionResult<ResponseWrapper<ReptDto>>> GetById(int id)
        {
            var user = await _userService.GetCurrentUserAsync(HttpContext);
            if (user == null) throw new UnauthorizedException();

            // Согласно матрице: Admin, Security, Teacher
            if (user.Role != UserRole.Admin && user.Role != UserRole.Security && user.Role != UserRole.Teacher)
            {
                throw new UnauthorizedException("You don't have access to reports.");
            }

            var report = await Repo.GetByIdAsync(id);
            if (report == null) throw new NotFoundException();

            // Check school access
            if (user.Role != UserRole.Admin && report.SchoolId != user.SchoolId)
            {
                throw new UnauthorizedException("You don't have access to this report.");
            }

            var dto = MapToDto(report);
            var response = new ResponseWrapper<ReptDto>(200, dto);
            return Ok(response);
        }

        [HttpDelete("{id:int}")]
        [Authorize(Policy = Policies.AdminOnly)]
        public override async Task<ActionResult<ResponseWrapper<object>>> Delete(int id)
        {
            return await base.Delete(id);
        }

        [HttpPost("generate")]
        public async Task<ActionResult<ResponseWrapper<ReptDto>>> GenerateReport([FromBody] ReptGenerateDto dto)
        {
            var user = await _userService.GetCurrentUserAsync(HttpContext);
            if (user == null) throw new UnauthorizedException();

            // Согласно матрице: Admin, Security, Teacher
            if (user.Role != Models.Enums.UserRole.Admin && user.Role != Models.Enums.UserRole.Security && user.Role != Models.Enums.UserRole.Teacher)
            {
                throw new UnauthorizedException("You don't have permission to generate reports.");
            }

            var targetSchoolId = user.Role != Models.Enums.UserRole.Admin ? user.SchoolId : dto.SchoolId;

            if (user.Role != Models.Enums.UserRole.Admin && targetSchoolId != user.SchoolId)
            {
                throw new BadRequestException("You can only generate reports for your school.");
            }

            // Get incidents and devices for the period
            var incidentsQuery = _context.Incidents
                .Where(i => i.SchoolId == targetSchoolId &&
                           i.Timestamp >= dto.PeriodStart.ToDateTime(TimeOnly.MinValue) &&
                           i.Timestamp <= dto.PeriodEnd.ToDateTime(TimeOnly.MaxValue))
                .AsQueryable();

            var devicesQuery = _context.Devices
                .Where(d => d.SchoolId == targetSchoolId)
                .AsQueryable();

            var incidents = await incidentsQuery.ToListAsync();
            var devices = await devicesQuery.ToListAsync();

            // Generate summary
            var summary = $"Звіт за період {dto.PeriodStart:dd.MM.yyyy} - {dto.PeriodEnd:dd.MM.yyyy}\n" +
                         $"Всього пристроїв: {devices.Count}\n" +
                         $"Активних пристроїв: {devices.Count(d => d.Status == Models.Enums.DeviceStatus.Active)}\n" +
                         $"Всього інцидентів: {incidents.Count}\n" +
                         $"Активних інцидентів: {incidents.Count(i => i.Status == Models.Enums.IncidentStatus.Active)}\n" +
                         $"Вирішених інцидентів: {incidents.Count(i => i.Status == Models.Enums.IncidentStatus.Resolved)}";

            var report = new Rept
            {
                SchoolId = targetSchoolId,
                GeneratedBy = user.Id,
                PeriodStart = dto.PeriodStart,
                PeriodEnd = dto.PeriodEnd,
                Summary = summary,
                GeneratedOn = DateTime.UtcNow
            };

            _context.Reports.Add(report);
            await _context.SaveChangesAsync();

            // Link incidents to report
            var reportIncidents = incidents.Select(incident => new ReptIncident
            {
                ReptId = report.Id,
                IncidentId = incident.Id
            }).ToList();

            if (reportIncidents.Any())
            {
                _context.ReptIncidents.AddRange(reportIncidents);
                await _context.SaveChangesAsync();
            }

            var reportDto = MapToDto(report);
            var response = new ResponseWrapper<ReptDto>(201, reportDto, "Report generated successfully");
            return CreatedAtAction(nameof(GetById), new { id = report.Id }, response);
        }

        [HttpGet("{id:int}/export")]
        public async Task<IActionResult> ExportReport(int id, [FromQuery] string format = "json")
        {
            var user = await _userService.GetCurrentUserAsync(HttpContext);
            if (user == null) throw new UnauthorizedException();

            // Согласно матрице: Admin, Security, Teacher
            if (user.Role != Models.Enums.UserRole.Admin && user.Role != Models.Enums.UserRole.Security && user.Role != Models.Enums.UserRole.Teacher)
            {
                throw new UnauthorizedException("You don't have access to export reports.");
            }

            var report = await _context.Reports
                .Include(r => r.School)
                .Include(r => r.Generator)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (report == null) throw new NotFoundException();

            // Check school access
            if (user.Role != Models.Enums.UserRole.Admin && report.SchoolId != user.SchoolId)
            {
                throw new UnauthorizedException("You don't have access to this report.");
            }

            // Get related incidents and devices
            var incidents = await _context.Incidents
                .Where(i => i.SchoolId == report.SchoolId &&
                           i.Timestamp >= report.PeriodStart.ToDateTime(TimeOnly.MinValue) &&
                           i.Timestamp <= report.PeriodEnd.ToDateTime(TimeOnly.MaxValue))
                .Include(i => i.Device)
                .Include(i => i.Reporter)
                .ToListAsync();

            var devices = await _context.Devices
                .Where(d => d.SchoolId == report.SchoolId)
                .ToListAsync();

            switch (format.ToLower())
            {
                case "csv":
                    return ExportToCsv(report, incidents, devices);
                case "json":
                default:
                    return ExportToJson(report, incidents, devices);
            }
        }

        private IActionResult ExportToJson(Rept report, List<Incident> incidents, List<Device> devices)
        {
            var exportData = new
            {
                Report = new
                {
                    report.Id,
                    report.SchoolId,
                    SchoolName = report.School?.Name,
                    report.PeriodStart,
                    report.PeriodEnd,
                    report.Summary,
                    report.GeneratedOn,
                    GeneratorName = report.Generator?.FullName
                },
                Devices = devices.Select(d => new
                {
                    d.Id,
                    d.DeviceName,
                    d.DeviceType,
                    d.Status,
                    d.Location
                }),
                Incidents = incidents.Select(i => new
                {
                    i.Id,
                    i.IncidentType,
                    i.Severity,
                    i.Status,
                    i.Timestamp,
                    DeviceName = i.Device?.DeviceName,
                    ReporterName = i.Reporter?.FullName
                })
            };

            var json = System.Text.Json.JsonSerializer.Serialize(exportData, new System.Text.Json.JsonSerializerOptions
            {
                WriteIndented = true
            });

            return File(System.Text.Encoding.UTF8.GetBytes(json), "application/json", $"report_{report.Id}.json");
        }

        private IActionResult ExportToCsv(Rept report, List<Incident> incidents, List<Device> devices)
        {
            var csv = new System.Text.StringBuilder();
            
            // Report header
            csv.AppendLine("Report Information");
            csv.AppendLine($"ID,{report.Id}");
            csv.AppendLine($"School ID,{report.SchoolId}");
            csv.AppendLine($"Period Start,{report.PeriodStart:yyyy-MM-dd}");
            csv.AppendLine($"Period End,{report.PeriodEnd:yyyy-MM-dd}");
            csv.AppendLine($"Generated On,{report.GeneratedOn:yyyy-MM-dd HH:mm:ss}");
            csv.AppendLine();

            // Devices
            csv.AppendLine("Devices");
            csv.AppendLine("ID,Device Name,Type,Status,Location");
            foreach (var device in devices)
            {
                csv.AppendLine($"{device.Id},{device.DeviceName},{device.DeviceType},{device.Status},{device.Location ?? ""}");
            }
            csv.AppendLine();

            // Incidents
            csv.AppendLine("Incidents");
            csv.AppendLine("ID,Type,Severity,Status,Timestamp,Device,Reporter");
            foreach (var incident in incidents)
            {
                csv.AppendLine($"{incident.Id},{incident.IncidentType},{incident.Severity},{incident.Status},{incident.Timestamp:yyyy-MM-dd HH:mm:ss},{incident.Device?.DeviceName ?? ""},{incident.Reporter?.FullName ?? ""}");
            }

            var bytes = System.Text.Encoding.UTF8.GetBytes(csv.ToString());
            return File(bytes, "text/csv", $"report_{report.Id}.csv");
        }
    }

    public class ReptGenerateDto
    {
        public int SchoolId { get; set; }
        public DateOnly PeriodStart { get; set; }
        public DateOnly PeriodEnd { get; set; }
    }
}
