// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolKeeper.Models.Enums;

#nullable disable

namespace SchoolKeeper.Migrations
{
    [DbContext(typeof(SchoolKeeperDbContext))]
    [Migration("20260421153639_PostgresProviderSwitch")]
    partial class PostgresProviderSwitch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceGuid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("device_guid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceTypeValue")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("device_type");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("StatusValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGuid")
                        .HasDatabaseName("IX_Device_DeviceGuid");

                    b.HasIndex("SchoolId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("incident_type");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("integer")
                        .HasColumnName("reported_by");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("SeverityValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("StatusValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("SchoolId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Incident");
                });

            modelBuilder.Entity("ParentStudent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("ParentId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudent");
                });

            modelBuilder.Entity("Rept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("integer")
                        .HasColumnName("generated_by");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_on");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("SchoolId");

                    b.ToTable("Rept");
                });

            modelBuilder.Entity("ReptIncident", b =>
                {
                    b.Property<int>("ReptId")
                        .HasColumnType("integer")
                        .HasColumnName("rept_id");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("ReptId", "IncidentId");

                    b.HasIndex("IncidentId");

                    b.ToTable("ReptIncident");
                });

            modelBuilder.Entity("School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("School");
                });

            modelBuilder.Entity("StudentTeacher", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudentTeacher");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UserIncident", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("IncidentId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "IncidentId");

                    b.HasIndex("IncidentId");

                    b.ToTable("UserIncident");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.HasOne("School", "School")
                        .WithMany("Devices")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("School");
                });

            modelBuilder.Entity("Incident", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithMany("Incidents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("User", "Reporter")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School", "School")
                        .WithMany("Incidents")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("Reporter");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ParentStudent", b =>
                {
                    b.HasOne("User", "Parent")
                        .WithMany("ParentRelationships")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Student")
                        .WithMany("StudentRelationships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Rept", b =>
                {
                    b.HasOne("User", "Generator")
                        .WithMany("GeneratedReports")
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("School", "School")
                        .WithMany("Reports")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generator");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ReptIncident", b =>
                {
                    b.HasOne("Incident", "Incident")
                        .WithMany("ReptIncidents")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rept", "Rept")
                        .WithMany("ReptIncidents")
                        .HasForeignKey("ReptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Rept");
                });

            modelBuilder.Entity("StudentTeacher", b =>
                {
                    b.HasOne("User", "Student")
                        .WithMany("StudentTeacherRelationships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Teacher")
                        .WithMany("TeacherStudentRelationships")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("UserIncident", b =>
                {
                    b.HasOne("Incident", "Incident")
                        .WithMany("UserIncidents")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("UserIncidents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Incident", b =>
                {
                    b.Navigation("ReptIncidents");

                    b.Navigation("UserIncidents");
                });

            modelBuilder.Entity("Rept", b =>
                {
                    b.Navigation("ReptIncidents");
                });

            modelBuilder.Entity("School", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Incidents");

                    b.Navigation("Reports");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("GeneratedReports");

                    b.Navigation("ParentRelationships");

                    b.Navigation("ReportedIncidents");

                    b.Navigation("StudentRelationships");

                    b.Navigation("StudentTeacherRelationships");

                    b.Navigation("TeacherStudentRelationships");

                    b.Navigation("UserIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
